### ISSUE TITLE
Error when USB-HUB remove

### ISSUE THREAD

**Issue by jesses2025smith** [Eric-Canas/USBMonitor#2]
Error when USB-HUB remove:

usbmonitor/__platform_specific_detectors/_linux_usb_detector.py", line 76, in __handle_device_event
    device_info = self.last_check_devices[device_id].copy()
                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: '/dev/bus/usb/001/026'

platform: Manjaro Linux distribute
python version: 3.11.5

**Comment by francisjeanneau** [comment]
Can confirm that this occurs not only with hubs, but with USB devices too.
```python
 Exception in thread Thread-2:
 Traceback (most recent call last):
   File "~/.environment/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
     self.run()
   File "~/.environment/lib/python3.11/site-packages/pyudev/monitor.py", line 544, in run
     self._callback(device)
   File "~/.environment/lib/python3.11/site-packages/usbmonitor/__platform_specific_detectors/_linux_usb_detector.py", line 76, in __handle_device_event
     device_info = self.last_check_devices[device_id].copy()
                   ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
 KeyError: '/dev/bus/usb/001/109'
```
This error breaks the monitoring deamon. No further connect or disconnect is detected past this point.

**Comment by Eric-Canas** [comment]
Thanks to @francisjeanneau for finding and solving the issue!
